export const OREDER_SET_TYPE = 'OREDER_SET_TYPE';
export const CATEGORY_LIST_REQUEST = 'CATEGORY_LIST_REQUEST';
export const CATEGORY_LIST_SUCCESS = 'CATEGORY_LIST_SUCCESS';
export const CATEGORY_LIST_FAIL = 'CATEGORY_LIST_FAIL';

export const PRODUCT_LIST_REQUEST = 'CATEGORY_LIST_REQUEST';
export const PRODUCT_LIST_SUCCESS = 'CATEGORY_LIST_SUCCESS';
export const PRODUCT_LIST_FAIL = 'CATEGORY_LIST_FAIL';